# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/imageclassify',
                'doc_host': 'https://Autobot37.github.io',
                'git_url': 'https://github.com/Autobot37/imageclassify',
                'lib_path': 'imageclassify'},
  'syms': {'imageclassify.core': {'imageclassify.core.foo': ('core.html#foo', 'imageclassify/core.py')}}}
